### ISSUE TITLE
analysis-examples/5-exploration-protocol.ipynb missing data in my binder

### ISSUE THREAD

**Issue by enidmagari** [anitagraser/movingpandas-examples#1]
FileNotFoundError: [Errno 2] No such file or directory: 'E:/Geodata/AISDK/raw_ais/aisdk_20170701.csv' when attempting to run example 5 in my binder

**Comment by anitagraser** [comment]
The file is rather large (2GB) and I am not certain if it is ok to use files of this size on MyBinder. That's the reason why I haven't included it in some form or other.

**Comment by anitagraser** [comment]
@enidmagari you can download the dataset from https://figshare.com/s/eae90f62ecca11a93540
