### ISSUE TITLE
Missing ship-data 

### ISSUE THREAD

**Issue by AlexNewn** [anitagraser/movingpandas-examples#10]
When trying to run ship-data example, the following data is not available : 

_FileNotFoundError: [Errno 2] No such file or directory: 'E:/Geodata/MarineCadastre/AIS_2021_03_28.zip'_

**Comment by anitagraser** [comment]
Thank you for the report. This cell should be removed from the notebook since it is wrong. The correct data loading code is shown in the following cell

read_file('../data/ais.gpkg')
