### ISSUE TITLE
Plot not showing in jupyter

### ISSUE THREAD

**Issue by jccmoing-bit** [anitagraser/movingpandas-examples#11]
when i run this code：my_traj.hvplot(width=500, height=300, line_width=7.0, tiles='OSM')，jupyter cannot display output

**Comment by anitagraser** [comment]
I cannot reproduce this issue. Are you certain that the environment is set up correctly? Try if hvplot results are displayed when you call the function on a regular GeoDataFrame. 

![image](https://user-images.githubusercontent.com/590385/178151243-2e6a762a-a317-421e-8bd9-0c29753bdfab.png)
