### ISSUE TITLE
Typo on OSM Trace Notebook example

### ISSUE THREAD

**Issue by tsmcgrath** [anitagraser/movingpandas-examples#5]
Very minor typo on OSM Trace Notebook. It's tiny so I assume you don't want a pull request. Happy to submit one. Let me know (tim@wanderfeast.com).

https://github.com/anitagraser/movingpandas-examples/blob/main/2-analysis-examples/5-osm-traces.ipynb

"Genearlizing and visualizing". Transposed a and r. Should be: Generalizing.

**Comment by anitagraser** [comment]
Thank you, Tim. Fixed.
