### ISSUE TITLE
Examples viewable in pre-executed notebook

### ISSUE THREAD

**Issue by r4ch45** [anitagraser/movingpandas-examples#6]
I'm looking to use movingpandas on a project and to get a feel for the functionality looking at the examples really helps, however I don't really want to run all the examples, just have a scan/search through them and the output for what I'm after. To help with this, it would be useful to have an executed version of the examples saved somewhere, either the notebooks themselves, or them in markdown/html.

**Comment by anitagraser** [comment]
Welcome, Rachel! I totally agree that we should have a rendered copy of the notebooks accessible somewhere. I haven't found a good (hopefully automated) solution yet, however. 

The rendered notebooks get quite large, particularly when holoviz graphics are involved. Therefore, I want to avoid adding the rendered notebooks directly to this repo. If you know of a solution for this issue, any recommendations are welcome.

**Comment by r4ch45** [comment]
Hello! Thanks for the speedy response (and for the library, looking forward to having a play).

Hmm I'm not sure. Could look at using https://nbautoexport.drivendata.org/stable/ to autogenerate the markdown (or html) - perhaps could create a pipeline to run and add the output somewhere else. I sometimes keep the output in my repos to help with pull requests, but might not help with the size issue that much unless can pipe it somewhere else.

**Comment by anitagraser** [comment]
I've created a new repo https://github.com/anitagraser/movingpandas-website to play around with and added badges that link to the rendered notebook htmls: 
![image](https://user-images.githubusercontent.com/590385/143081094-278af673-aabe-4889-a188-00ec773bf5d4.png)

**Comment by r4ch45** [comment]
Nice one - thanks!

**Comment by anitagraser** [comment]
The analysis examples should all be viewable now.

**Comment by r4ch45** [comment]
Awesome! Thank you!
